# Generated by Django 4.0.1 on 2022-11-07 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_article', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_fournisseur', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_site', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_commande', models.IntegerField(default=0)),
                ('quantite_recue', models.IntegerField(default=0)),
                ('ecart', models.IntegerField(default=0)),
                ('date_commande', models.DateTimeField(verbose_name='Date de Commande')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commande.article')),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commande.fournisseur')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commande.site')),
            ],
        ),
    ]
