# Generated by Django 4.0.1 on 2022-11-10 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commande', '0004_commande_num_cmd'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commande',
            old_name='num_cmd',
            new_name='lignecommande',
        ),
    ]
